import type { CandidateProfile } from "./matching";

export const sampleCandidates: CandidateProfile[] = [
  {
    id: "mara-visual-city",
    firstName: "Mara",
    city: "Athens",
    world: "documentary photography and urban observation",
    curiosity: ["overlooked city details", "how people inhabit public space", "biology as visual structure"],
    conversationStyle: ["long one-to-one conversations", "observational", "comfortable with silence"],
    temperament: ["quietly social", "spontaneous walks", "small groups"],
    wants: ["someone intellectually rigorous outside the arts", "a person who notices systems behind everyday life"],
    notThis: ["personal branding", "networking events"],
    intention: "meet someone who can make familiar things look conceptually strange again",
    note: "Often walks through Athens without a destination and photographs unnoticed transitions in the city.",
  },
  {
    id: "nikos-founder",
    firstName: "Nikos",
    city: "Athens",
    world: "startup strategy and technology entrepreneurship",
    curiosity: ["AI products", "growth systems", "venture capital", "behavioral economics"],
    conversationStyle: ["fast debate", "high energy", "idea pitching"],
    temperament: ["social", "competitive", "event-oriented"],
    wants: ["ambitious collaborators", "people building companies"],
    notThis: ["slow conversations without an outcome"],
    intention: "meet people who might become collaborators or cofounders",
    note: "Runs founder dinners and frequently attends professional networking events.",
  },
  {
    id: "eleni-architect",
    firstName: "Eleni",
    city: "Athens",
    world: "architecture, adaptive reuse and old buildings",
    curiosity: ["abandoned structures", "memory embedded in places", "material decay", "city history"],
    conversationStyle: ["deep conversations", "questions before opinions", "likes conceptual detours"],
    temperament: ["reserved", "curious", "walks rather than parties"],
    wants: ["someone from science who thinks about systems differently", "people with unusual obsessions"],
    notThis: ["career networking", "status-driven social scenes"],
    intention: "find someone whose professional world is distant from mine but whose curiosity feels familiar",
    note: "Keeps a private archive of buildings that have changed use over time.",
  },
  {
    id: "thanos-clinician",
    firstName: "Thanos",
    city: "Athens",
    world: "clinical medicine and hospital research",
    curiosity: ["medical evidence", "clinical trials", "health technology"],
    conversationStyle: ["technical discussion", "evidence-first", "direct"],
    temperament: ["structured", "professional", "time-conscious"],
    wants: ["other clinicians interested in research", "professional exchange"],
    notThis: ["unstructured artistic conversations"],
    intention: "meet doctors who may collaborate on research projects",
    note: "Most social activity happens through hospital and conference networks.",
  },
  {
    id: "iris-musician",
    firstName: "Iris",
    city: "Athens",
    world: "experimental music, sound art and field recording",
    curiosity: ["strange sounds", "obsolete technology", "urban acoustics", "how attention changes perception"],
    conversationStyle: ["playful but deep", "comfortable with abstraction", "likes odd questions"],
    temperament: ["independent", "quiet", "exploratory"],
    wants: ["someone outside music with a serious curiosity", "people who enjoy difficult or obscure things without performing expertise"],
    notThis: ["music industry networking", "influencer culture"],
    intention: "meet someone from a completely different field who is genuinely fascinated by obscure things",
    note: "Records mechanical and environmental sounds around Athens and builds compositions from them.",
  },
  {
    id: "petros-designer",
    firstName: "Petros",
    city: "Athens",
    world: "interaction design and digital products",
    curiosity: ["human behavior", "interface design", "technology", "cities"],
    conversationStyle: ["idea-driven", "visual", "collaborative"],
    temperament: ["social", "curious", "moderately spontaneous"],
    wants: ["people who understand humans deeply", "people outside product design"],
    notThis: ["purely commercial conversations"],
    intention: "meet someone who can challenge how I think about human behavior",
    note: "Designs software but spends free time sketching interactions observed in cafés and stations.",
  },
  {
    id: "sophia-historian",
    firstName: "Sophia",
    city: "Athens",
    world: "social history and archival research",
    curiosity: ["forgotten lives", "how institutions shape people", "old documents", "urban memory"],
    conversationStyle: ["slow", "story-rich", "asks many questions", "likes long conversations"],
    temperament: ["calm", "one-to-one", "reflective"],
    wants: ["someone who thinks scientifically but is interested in human stories", "a different way of interpreting evidence"],
    notThis: ["networking", "loud social scenes"],
    intention: "meet someone who uses evidence in a completely different way from historians",
    note: "Likes conversations where two people bring different kinds of evidence to the same question.",
  },
  {
    id: "alex-chef",
    firstName: "Alex",
    city: "Athens",
    world: "restaurant kitchens, fermentation and food culture",
    curiosity: ["microbiology of fermentation", "craft", "regional food traditions", "sensory memory"],
    conversationStyle: ["storytelling", "practical", "warm", "curious"],
    temperament: ["energetic", "hands-on", "social in small groups"],
    wants: ["people who know science but are not trying to network", "people obsessed with how things work"],
    notThis: ["business pitching", "food influencer culture"],
    intention: "meet someone who can explain the invisible science behind everyday things",
    note: "Experiments with fermentation and keeps notebooks on failures as carefully as successes.",
  },
  {
    id: "anna-lawyer",
    firstName: "Anna",
    city: "Athens",
    world: "corporate law and regulatory work",
    curiosity: ["institutions", "risk", "negotiation", "policy"],
    conversationStyle: ["precise", "argumentative", "structured debate"],
    temperament: ["formal", "driven", "socially confident"],
    wants: ["sharp debaters", "professionally accomplished people"],
    notThis: ["open-ended conversations without a clear point"],
    intention: "meet someone intellectually competitive who enjoys debate",
    note: "Enjoys adversarial discussion and tends to treat disagreement as a way of testing ideas.",
  },
  {
    id: "leon-maker",
    firstName: "Leon",
    city: "Athens",
    world: "electronics repair, analog synthesizers and making physical things",
    curiosity: ["obsolete technology", "how systems fail", "repair culture", "sound"],
    conversationStyle: ["quiet", "technical when invited", "likes explaining through objects"],
    temperament: ["reserved", "patient", "deeply focused"],
    wants: ["someone from biology or medicine who likes mechanisms", "people who care about overlooked technical details"],
    notThis: ["startup networking", "status games"],
    intention: "meet someone who has a different kind of technical mind and likes taking things apart conceptually",
    note: "Repairs instruments others throw away and is more interested in failure modes than new products.",
  },
  {
    id: "daphne-curator",
    firstName: "Daphne",
    city: "Athens",
    world: "contemporary art curation and cultural programming",
    curiosity: ["how ideas change across disciplines", "visual culture", "scientific images", "public space"],
    conversationStyle: ["exploratory", "conceptual", "likes connecting distant fields"],
    temperament: ["social but selective", "curious", "comfortable with ambiguity"],
    wants: ["scientists who are culturally curious", "people who can explain a difficult field without flattening it"],
    notThis: ["self-promotion", "transactional networking"],
    intention: "meet someone whose expertise is far from art but whose questions overlap with mine",
    note: "Frequently builds exhibitions around unexpected collisions between disciplines.",
  },
  {
    id: "giorgos-finance",
    firstName: "Giorgos",
    city: "Athens",
    world: "investment analysis and financial markets",
    curiosity: ["markets", "macroeconomics", "business strategy", "performance"],
    conversationStyle: ["fast", "competitive", "results-focused"],
    temperament: ["high energy", "network-oriented", "socially active"],
    wants: ["high-achieving professionals", "investment opportunities"],
    notThis: ["slow abstract conversation", "artistic ambiguity"],
    intention: "expand my professional network with people doing ambitious work",
    note: "Uses social events mainly to discover professional opportunities.",
  },
];
